steps:
  # 1. Build the container image using the official Docker Hub 'docker' image
  - name: 'docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/g-cav-repo/data-processor-job:latest',
        './data-processor-job',
      ]

  # 2. Push the container image to Artifact Registry
  - name: 'docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/g-cav-repo/data-processor-job:latest',
      ]

  # 3. Deploy the new image using the official Docker Hub 'google/cloud-sdk' image
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'jobs',
        'update',
        'data-processor-job',
        '--image',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/g-cav-repo/data-processor-job:latest',
        '--region',
        'us-central1',
        '--service-account',
        'data-processor-sa@${PROJECT_ID}.iam.gserviceaccount.com',
      ]

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/g-cav-repo/data-processor-job:latest'

options:
  logging: CLOUD_LOGGING_ONLY